/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.eleva.eleva.View;

/**
 *
 * @author Gustavo
 */
public class formPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form formPrincipal
     */
    public formPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnLogin1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCandidato = new javax.swing.JButton();
        btnRecrutador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(980, 700));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(53, 53, 140));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 2, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eleva");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 30, 140, 40);

        btnLogin.setBackground(new java.awt.Color(53, 53, 140));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setToolTipText("");
        btnLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin);
        btnLogin.setBounds(720, 20, 110, 60);

        btnLogin1.setBackground(new java.awt.Color(53, 53, 140));
        btnLogin1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLogin1.setText("Sair");
        btnLogin1.setToolTipText("");
        btnLogin1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin1);
        btnLogin1.setBounds(850, 20, 110, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 970, 100);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Sou Candidato");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(520, 230, 240, 50);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Cadastre seu perfil e encontre as melhores oportunidades");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 270, 340, 16);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Sou Recrutador");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 230, 240, 40);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cadastre seu perfil e encontre as melhores oportunidades");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(520, 270, 340, 16);

        btnCandidato.setBackground(new java.awt.Color(239, 239, 239));
        btnCandidato.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCandidato.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.white));
        btnCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCandidatoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCandidato);
        btnCandidato.setBounds(500, 140, 450, 160);

        btnRecrutador.setBackground(new java.awt.Color(239, 239, 239));
        btnRecrutador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRecrutador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, java.awt.Color.white));
        btnRecrutador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecrutadorActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecrutador);
        btnRecrutador.setBounds(30, 140, 420, 160);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 970, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        formLogin login = new formLogin();
        login.setVisible(true); // Torna a SegundaTela visível

        // Fecha a TelaInicial
        this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRecrutadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecrutadorActionPerformed
        formCadastroRecrutador recrutador = new formCadastroRecrutador();
        recrutador.setVisible(true); // Torna a SegundaTela visível

        // Fecha a TelaInicial
        this.dispose();
    }//GEN-LAST:event_btnRecrutadorActionPerformed

    private void btnCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCandidatoActionPerformed
        formCadastro funcionario = new formCadastro();
        funcionario.setVisible(true); // Torna a SegundaTela visível

        // Fecha a TelaInicial
        this.dispose();
    }//GEN-LAST:event_btnCandidatoActionPerformed

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnLogin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCandidato;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JButton btnRecrutador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
