/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.eleva.eleva.View;

import com.eleva.eleva.Controller.DatabaseManager;
import com.eleva.eleva.Model.classAtualizaEmpresa;
import com.eleva.eleva.Model.classCarregaEmpresa;
import com.eleva.eleva.Model.classConfirmaEmpresa;
import com.eleva.eleva.Model.classEmail;
import com.eleva.eleva.Model.classExclusaoEmpresa;
import com.eleva.eleva.Model.classValidaCampos;
import javax.swing.JOptionPane;
import com.eleva.eleva.Model.classValidaRecrutador;

/**
 *
 * @author Gustavo
 */
public class formPerfilEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form formPerfilEmpresa
     */
    public static String Empresa;
    public static String emailEmpresa;
    
    public String senhaAnterior;
    public String sAreaAtuacao;
    public String sCEP;
    public String sCNPJ;
    public String sContato;
    public String sEmail;
    public String sEndereco;
    public String sSenha; 
    public String sResumoEmpresa;
    public String sNomeResponsavel; 
    public String pathCurriculo;
    public String sEmpresa;
    
    public formPerfilEmpresa(String email) {
        initComponents(); 
        emailEmpresa = email;
        carregaDados(emailEmpresa);
        senhaAnterior = new String(tfSenha.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnSair1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        tfAtuacao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfResumo = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        tfSenha = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnCadastro = new javax.swing.JButton();
        tfCEP = new javax.swing.JFormattedTextField();
        tfNomeResponsavel = new javax.swing.JTextField();
        tfEndereco = new javax.swing.JTextField();
        tfEmpresa = new javax.swing.JTextField();
        tfCNPJ = new javax.swing.JFormattedTextField();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(53, 53, 140));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 2, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eleva");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 30, 140, 40);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        btnSair1.setBackground(new java.awt.Color(242, 245, 247));
        btnSair1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSair1.setForeground(new java.awt.Color(0, 0, 0));
        btnSair1.setText("Sair");
        btnSair1.setBorder(null);
        btnSair1.setBorderPainted(false);
        jPanel4.add(btnSair1);
        btnSair1.setBounds(420, 610, 70, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Editar Perfil");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(400, 20, 150, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Senha");
        jLabel3.setToolTipText("");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(40, 250, 80, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nome Responsável");
        jLabel4.setToolTipText("");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(40, 110, 120, 16);

        btnSair.setBackground(new java.awt.Color(242, 245, 247));
        btnSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSair.setForeground(new java.awt.Color(0, 0, 0));
        btnSair.setText("Sair");
        btnSair.setBorder(null);
        btnSair.setBorderPainted(false);
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel4.add(btnSair);
        btnSair.setBounds(430, 490, 70, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("E-mail");
        jLabel5.setToolTipText("");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(40, 180, 80, 16);

        tfEmail.setBackground(new java.awt.Color(234, 237, 239));
        tfEmail.setForeground(new java.awt.Color(0, 0, 0));
        tfEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(tfEmail);
        tfEmail.setBounds(40, 200, 280, 40);

        tfAtuacao.setBackground(new java.awt.Color(234, 237, 239));
        tfAtuacao.setForeground(new java.awt.Color(0, 0, 0));
        tfAtuacao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(tfAtuacao);
        tfAtuacao.setBounds(640, 130, 280, 40);

        tfResumo.setBackground(new java.awt.Color(234, 237, 239));
        tfResumo.setColumns(20);
        tfResumo.setForeground(new java.awt.Color(0, 0, 0));
        tfResumo.setRows(5);
        tfResumo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(tfResumo);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(640, 210, 280, 170);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Área de atuação empresarial");
        jLabel8.setToolTipText("");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(640, 110, 190, 16);

        tfSenha.setBackground(new java.awt.Color(234, 236, 238));
        tfSenha.setForeground(new java.awt.Color(0, 0, 0));
        tfSenha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(tfSenha);
        tfSenha.setBounds(40, 270, 280, 40);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("CNPJ");
        jLabel9.setToolTipText("");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(340, 110, 80, 16);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Empresa");
        jLabel10.setToolTipText("");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(340, 180, 80, 16);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Resumo sobre a empresa");
        jLabel11.setToolTipText("");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(640, 190, 200, 16);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Endereço");
        jLabel12.setToolTipText("");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(340, 320, 80, 16);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("CEP");
        jLabel13.setToolTipText("");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(340, 250, 80, 16);

        btnCadastro.setBackground(new java.awt.Color(229, 229, 229));
        btnCadastro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCadastro.setForeground(new java.awt.Color(51, 51, 51));
        btnCadastro.setText("Confirmar Edição");
        btnCadastro.setBorder(null);
        btnCadastro.setBorderPainted(false);
        btnCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        jPanel4.add(btnCadastro);
        btnCadastro.setBounds(370, 430, 200, 50);

        tfCEP.setBackground(new java.awt.Color(234, 237, 239));
        tfCEP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfCEP.setForeground(new java.awt.Color(0, 0, 0));
        try {
            tfCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel4.add(tfCEP);
        tfCEP.setBounds(340, 270, 280, 40);

        tfNomeResponsavel.setBackground(new java.awt.Color(234, 237, 239));
        tfNomeResponsavel.setForeground(new java.awt.Color(0, 0, 0));
        tfNomeResponsavel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(tfNomeResponsavel);
        tfNomeResponsavel.setBounds(40, 130, 280, 40);

        tfEndereco.setBackground(new java.awt.Color(234, 237, 239));
        tfEndereco.setForeground(new java.awt.Color(0, 0, 0));
        tfEndereco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(tfEndereco);
        tfEndereco.setBounds(340, 340, 280, 40);

        tfEmpresa.setBackground(new java.awt.Color(234, 237, 239));
        tfEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        tfEmpresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(tfEmpresa);
        tfEmpresa.setBounds(340, 200, 280, 40);

        tfCNPJ.setBackground(new java.awt.Color(234, 237, 239));
        tfCNPJ.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfCNPJ.setForeground(new java.awt.Color(0, 0, 0));
        try {
            tfCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel4.add(tfCNPJ);
        tfCNPJ.setBounds(340, 130, 280, 40);

        btnExcluir.setBackground(new java.awt.Color(229, 229, 229));
        btnExcluir.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(204, 0, 0));
        btnExcluir.setText("X");
        btnExcluir.setToolTipText("Excluir Conta");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel4.add(btnExcluir);
        btnExcluir.setBounds(870, 440, 50, 40);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        formPrincipal principal1 = new formPrincipal();
        principal1.setVisible(true); // Torna a SegundaTela visível

        // Fecha a TelaInicial
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed
    
    private void carregaDados(String email) {
        try {
            classCarregaEmpresa dados = DatabaseManager.carregarDadosEmpresa(email);

            this.sNomeResponsavel = dados.NomeResponsavel;  
            this.sSenha = dados.Senha; 
            this.sCNPJ = dados.CNPJ;
            this.sEmail = dados.Email; 
            this.sEndereco = dados.Endereco;
            this.sAreaAtuacao = dados.AreaAtuacao;
            this.sResumoEmpresa = dados.ResumoEmpresa;
            this.sCEP = dados.CEP; 
            this.sEmpresa = dados.Empresa;

            // Agora você pode popular os campos da tela se quiser:
            tfNomeResponsavel.setText(sNomeResponsavel);
            tfEmail.setText(sEmail); 
            tfEndereco.setText(sEndereco);
            tfAtuacao.setText(sAreaAtuacao);
            tfResumo.setText(sResumoEmpresa);
            tfCEP.setText(sCEP);
            tfCNPJ.setText(sCNPJ);
            tfSenha.setText(sSenha);
            tfEmpresa.setText(sEmpresa);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar dados! Verifique com o suporte", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        if (!classValidaRecrutador.ValidacaoCadastroRecrutador(tfAtuacao, tfCEP, tfCNPJ, tfNomeResponsavel, tfEmail, tfEndereco, tfResumo, tfSenha, tfSenha)) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        } 
        if (!classEmail.Validacao(tfEmail.getText())){
            JOptionPane.showMessageDialog(this, "Digite um endereço de e-mail valido!", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        GuardarDados();
        if (!classValidaCampos.ValidaLength(sEmail, sSenha, sAreaAtuacao, sEndereco, sCEP, sResumoEmpresa, sNomeResponsavel, null, sEmpresa, "Empresa")){
            JOptionPane.showMessageDialog(this, "Ajuste o tamanho dos campos!", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        }else {
            // Se a validação passar, você pode prosseguir com o cadastro 
            if (classConfirmaEmpresa.confirmaEmpresa(senhaAnterior, tfSenha, sNomeResponsavel, sEmail, sCNPJ, sEmpresa, sCEP, sEndereco, sAreaAtuacao, sResumoEmpresa)){
                formPrincipal principal1 = new formPrincipal();
                principal1.setVisible(true);  

                this.dispose();
            }
        }
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (classExclusaoEmpresa.confirmaExclusao(tfCNPJ.getText(), senhaAnterior)){
           JOptionPane.showMessageDialog(this, "Exclusão realizada com sucesso!", "Erro", javax.swing.JOptionPane.WARNING_MESSAGE);
           
           formPrincipal principal1 = new formPrincipal();
           principal1.setVisible(true);  

           // Fecha a TelaInicial
           this.dispose();
        }
        else{
           JOptionPane.showMessageDialog(this, "Exclusão cancelada!", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
    
    private void GuardarDados(){
        sAreaAtuacao = tfAtuacao.getText();
        sCEP = tfCEP.getText();
        sCNPJ = tfCNPJ.getText(); 
        sEmail = tfEmail.getText();
        sEndereco = tfEndereco.getText();
        char[] senhaArray = tfSenha.getPassword();
        sSenha = new String(senhaArray); 
        sResumoEmpresa = tfResumo.getText();
        sNomeResponsavel = tfNomeResponsavel.getText(); 
        sEmpresa = tfEmpresa.getText();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPerfilEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPerfilEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPerfilEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPerfilEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPerfilEmpresa(emailEmpresa).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSair1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfAtuacao;
    private javax.swing.JFormattedTextField tfCEP;
    private javax.swing.JFormattedTextField tfCNPJ;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEmpresa;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfNomeResponsavel;
    private javax.swing.JTextArea tfResumo;
    private javax.swing.JPasswordField tfSenha;
    // End of variables declaration//GEN-END:variables
}
