/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.eleva.eleva.View;

import com.eleva.eleva.Controller.DatabaseManager;
import com.eleva.eleva.Model.classAtualizaTabelasAux;
import com.eleva.eleva.Model.classCarregaCandidatos;
import com.eleva.eleva.Model.classConfirmaCandidato;
import com.eleva.eleva.Model.classCurriculo;
import com.eleva.eleva.Model.classEmail; 
import com.eleva.eleva.Model.classExclusaoCandidato;
import com.eleva.eleva.Model.classMensageria;
import com.eleva.eleva.Model.classValidaCampos;
import com.eleva.eleva.Model.classValidaCandidato;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gustavo
 */
public class formPerfilCandidato extends javax.swing.JFrame {

    /**
     * Creates new form formPerfilCandidato
     */
    
     
    
    String senhaAnterior;
    
    public String filename;
    public static String Usuario;
    public static String emailUsuario;
    public String nome;  
    public String Senha;  
    public String CPF;
    public String Email;
    public String Contato ;
    public String Endereco ;
    public String Experiencia ;
    public String Resumo ;
    public String CEP ;
    public String Nascimento ;
    public byte[] curriculoCandidato;
    
    public formPerfilCandidato(String tipoUsuario, String email) {
        initComponents();
        Usuario = tipoUsuario;
        emailUsuario = email;
        VerificaVisivel();
        carregaDados(emailUsuario);
        senhaAnterior = new String(tfSenha.getPassword());
        setaImagem(); 
    }
    
     // Setter para receber o nome

    public formPerfilCandidato() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSair1 = new javax.swing.JButton();
        btnCadastro = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnEdicao = new javax.swing.JButton();
        tfEmail = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        tfExperiencia = new javax.swing.JTextField();
        tfEndereco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        btnCurriculo = new javax.swing.JButton();
        btnEditarCurriculo = new javax.swing.JButton();
        labelSenha = new javax.swing.JLabel();
        tfCEP = new javax.swing.JFormattedTextField();
        tfContato = new javax.swing.JFormattedTextField();
        tfSenha = new javax.swing.JPasswordField();
        tfCPF = new javax.swing.JTextField();
        labelCPF = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfResumo = new javax.swing.JTextArea();
        btnExcluir = new javax.swing.JButton();
        tfDataNascimento = new javax.swing.JFormattedTextField();
        labelNascimento1 = new javax.swing.JLabel();
        btnMensageria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(53, 53, 140));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 2, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eleva");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 30, 140, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        btnSair1.setBackground(new java.awt.Color(242, 245, 247));
        btnSair1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSair1.setForeground(new java.awt.Color(0, 0, 0));
        btnSair1.setText("Sair");
        btnSair1.setBorder(null);
        btnSair1.setBorderPainted(false);
        jPanel1.add(btnSair1);
        btnSair1.setBounds(420, 610, 70, 30);

        btnCadastro.setBackground(new java.awt.Color(229, 229, 229));
        btnCadastro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCadastro.setForeground(new java.awt.Color(51, 51, 51));
        btnCadastro.setText("Confirmar Cadastro");
        btnCadastro.setBorder(null);
        btnCadastro.setBorderPainted(false);
        jPanel1.add(btnCadastro);
        btnCadastro.setBounds(360, 550, 200, 50);

        btnSair.setBackground(new java.awt.Color(242, 245, 247));
        btnSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSair.setForeground(new java.awt.Color(0, 0, 0));
        btnSair.setText("Sair");
        btnSair.setBorder(null);
        btnSair.setBorderPainted(false);
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair);
        btnSair.setBounds(710, 470, 70, 30);

        btnEdicao.setBackground(new java.awt.Color(229, 229, 229));
        btnEdicao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEdicao.setForeground(new java.awt.Color(51, 51, 51));
        btnEdicao.setText("Confirmar Edição");
        btnEdicao.setBorder(null);
        btnEdicao.setBorderPainted(false);
        btnEdicao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdicaoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdicao);
        btnEdicao.setBounds(640, 410, 210, 50);

        tfEmail.setBackground(new java.awt.Color(234, 236, 238));
        tfEmail.setForeground(new java.awt.Color(0, 0, 0));
        tfEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfEmail.setEnabled(false);
        jPanel1.add(tfEmail);
        tfEmail.setBounds(30, 290, 260, 40);

        tfNome.setBackground(new java.awt.Color(234, 236, 238));
        tfNome.setForeground(new java.awt.Color(0, 0, 0));
        tfNome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfNome.setEnabled(false);
        jPanel1.add(tfNome);
        tfNome.setBounds(30, 220, 260, 40);

        tfExperiencia.setBackground(new java.awt.Color(234, 236, 238));
        tfExperiencia.setForeground(new java.awt.Color(0, 0, 0));
        tfExperiencia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfExperiencia.setEnabled(false);
        jPanel1.add(tfExperiencia);
        tfExperiencia.setBounds(320, 220, 260, 40);

        tfEndereco.setBackground(new java.awt.Color(234, 236, 238));
        tfEndereco.setForeground(new java.awt.Color(0, 0, 0));
        tfEndereco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfEndereco.setEnabled(false);
        jPanel1.add(tfEndereco);
        tfEndereco.setBounds(320, 290, 260, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("E-mail");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 270, 120, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Contato");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(320, 340, 120, 16);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Endereço");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(320, 270, 120, 16);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Resumo Profissional");
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(600, 200, 120, 16);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Experiência");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(320, 200, 120, 16);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("CEP");
        jLabel9.setToolTipText("");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 340, 120, 16);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Nome Completo");
        jLabel11.setToolTipText("");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 200, 120, 16);

        lblImagem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblImagem);
        lblImagem.setBounds(30, 20, 150, 150);

        btnCurriculo.setBackground(new java.awt.Color(229, 229, 229));
        btnCurriculo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCurriculo.setForeground(new java.awt.Color(51, 51, 51));
        btnCurriculo.setText("Baixar Curriculo");
        btnCurriculo.setBorder(null);
        btnCurriculo.setBorderPainted(false);
        btnCurriculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCurriculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurriculoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCurriculo);
        btnCurriculo.setBounds(190, 140, 120, 30);

        btnEditarCurriculo.setBackground(new java.awt.Color(229, 229, 229));
        btnEditarCurriculo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditarCurriculo.setForeground(new java.awt.Color(51, 51, 51));
        btnEditarCurriculo.setText("Editar Curriculo");
        btnEditarCurriculo.setBorder(null);
        btnEditarCurriculo.setBorderPainted(false);
        btnEditarCurriculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarCurriculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCurriculoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarCurriculo);
        btnEditarCurriculo.setBounds(190, 20, 120, 30);

        labelSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelSenha.setForeground(new java.awt.Color(0, 0, 0));
        labelSenha.setText("Senha");
        labelSenha.setToolTipText("");
        jPanel1.add(labelSenha);
        labelSenha.setBounds(30, 410, 120, 16);

        tfCEP.setBackground(new java.awt.Color(234, 237, 239));
        tfCEP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfCEP.setForeground(new java.awt.Color(0, 0, 0));
        try {
            tfCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCEP.setEnabled(false);
        jPanel1.add(tfCEP);
        tfCEP.setBounds(30, 360, 260, 40);

        tfContato.setBackground(new java.awt.Color(234, 237, 239));
        tfContato.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfContato.setForeground(new java.awt.Color(0, 0, 0));
        try {
            tfContato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfContato.setEnabled(false);
        jPanel1.add(tfContato);
        tfContato.setBounds(320, 360, 260, 40);

        tfSenha.setBackground(new java.awt.Color(234, 236, 238));
        tfSenha.setForeground(new java.awt.Color(0, 0, 0));
        tfSenha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfSenha.setEnabled(false);
        jPanel1.add(tfSenha);
        tfSenha.setBounds(30, 430, 260, 40);

        tfCPF.setBackground(new java.awt.Color(234, 236, 238));
        tfCPF.setForeground(new java.awt.Color(0, 0, 0));
        tfCPF.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfCPF.setEnabled(false);
        jPanel1.add(tfCPF);
        tfCPF.setBounds(320, 430, 260, 40);

        labelCPF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelCPF.setForeground(new java.awt.Color(0, 0, 0));
        labelCPF.setText("CPF");
        labelCPF.setToolTipText("");
        jPanel1.add(labelCPF);
        labelCPF.setBounds(320, 410, 120, 16);

        tfResumo.setBackground(new java.awt.Color(234, 237, 239));
        tfResumo.setColumns(20);
        tfResumo.setForeground(new java.awt.Color(0, 0, 0));
        tfResumo.setRows(5);
        tfResumo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfResumo.setEnabled(false);
        jScrollPane1.setViewportView(tfResumo);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(600, 220, 280, 170);

        btnExcluir.setBackground(new java.awt.Color(229, 229, 229));
        btnExcluir.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(204, 0, 0));
        btnExcluir.setText("X");
        btnExcluir.setToolTipText("Excluir Conta");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir);
        btnExcluir.setBounds(830, 20, 50, 40);

        tfDataNascimento.setBackground(new java.awt.Color(234, 237, 239));
        tfDataNascimento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfDataNascimento.setForeground(new java.awt.Color(0, 0, 0));
        tfDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        tfDataNascimento.setEnabled(false);
        jPanel1.add(tfDataNascimento);
        tfDataNascimento.setBounds(30, 430, 110, 40);

        labelNascimento1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelNascimento1.setForeground(new java.awt.Color(0, 0, 0));
        labelNascimento1.setText("Data de Nascimento");
        labelNascimento1.setToolTipText("");
        jPanel1.add(labelNascimento1);
        labelNascimento1.setBounds(30, 410, 120, 16);

        btnMensageria.setBackground(new java.awt.Color(229, 229, 229));
        btnMensageria.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnMensageria.setForeground(new java.awt.Color(0, 153, 0));
        btnMensageria.setText("!");
        btnMensageria.setToolTipText("Excluir Conta");
        btnMensageria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMensageria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMensageriaActionPerformed(evt);
            }
        });
        jPanel1.add(btnMensageria);
        btnMensageria.setBounds(830, 70, 50, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdicaoActionPerformed
        if (!classValidaCandidato.ValidacaoCadastroCandidato(tfNome, tfExperiencia, tfCEP, tfCPF, tfContato, tfEmail, tfEndereco, tfResumo, tfSenha, tfSenha, curriculoCandidato, "Atualização")) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        } 
        if (!classEmail.Validacao(tfEmail.getText())){
            JOptionPane.showMessageDialog(this, "Digite um endereço de e-mail valido!", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        GuardarDados();
        if (!classValidaCampos.ValidaLength(Email, Senha, Experiencia, Endereco, CEP, Resumo, nome, Contato, nome, "Empresa")){
            JOptionPane.showMessageDialog(this, "Ajuste o tamanho dos campos!", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        }else {
            // Se a validação passar, você pode prosseguir com a edição
            if (!classAtualizaTabelasAux.atualizaAux(Email, senhaAnterior)){
               JOptionPane.showMessageDialog(this, "Erro na atualização de e-mail!", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE); 
               return;
            }
                    
            if (classConfirmaCandidato.confirmaCandidato(senhaAnterior, tfSenha, tfExperiencia.getText(), tfCEP.getText(), CPF, tfContato.getText(), 
            tfEmail.getText(), tfEndereco.getText(), tfResumo.getText(), tfNome.getText(), curriculoCandidato)){
                formPrincipal principal1 = new formPrincipal();
                principal1.setVisible(true);  
 
                this.dispose();
            }   
        }
         
    }//GEN-LAST:event_btnEdicaoActionPerformed
    
    private void carregaDados(String email) {
        try {
            classCarregaCandidatos dados = DatabaseManager.carregarDadosCandidato(email);

            this.nome = dados.nome;  
            this.Senha = dados.senha; 
            this.CPF = dados.cpf;
            this.Email = dados.email;
            this.Contato = dados.contato;
            this.Endereco = dados.endereco;
            this.Experiencia = dados.experiencia;
            this.Resumo = dados.resumo;
            this.CEP = dados.cep;
            this.curriculoCandidato = dados.curriculo;
            this.Nascimento = dados.nascimento;

            // Agora você pode popular os campos da tela se quiser:
            tfNome.setText(nome);
            tfEmail.setText(Email);
            tfContato.setText(Contato);
            tfEndereco.setText(Endereco);
            tfExperiencia.setText(Experiencia);
            tfResumo.setText(Resumo);
            tfCEP.setText(CEP);
            tfCPF.setText(CPF);
            tfSenha.setText(Senha);
            tfDataNascimento.setText(Nascimento);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar dados! Verifique com o suporte", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    
    private void GuardarDados(){
        Experiencia = tfExperiencia.getText();
        CEP = tfCEP.getText(); 
        Contato = tfContato.getText();
        Email = tfEmail.getText();
        Endereco = tfEndereco.getText();
        char[] senhaArray = tfSenha.getPassword();
        Senha = new String(senhaArray); 
        Resumo = tfResumo.getText();
        nome = tfNome.getText();
    }
    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        
        if (Usuario.equals("Recrutador")){
            formRecrutador recrutador = new formRecrutador();
            recrutador.setVisible(true); // Torna a SegundaTela visível
        
        }else if (Usuario.equals("Candidato")){
            formPrincipal principal = new formPrincipal();
            principal.setVisible(true); // Torna a SegundaTela visível
        }
         
        // Fecha a TelaInicial
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnEditarCurriculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCurriculoActionPerformed
        curriculoCandidato = classCurriculo.editarCurriculo();
    }//GEN-LAST:event_btnEditarCurriculoActionPerformed

    private void btnCurriculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurriculoActionPerformed
        //sclassCurriculo.salvarCurriculo(curriculoCandidato); 
    }//GEN-LAST:event_btnCurriculoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (classExclusaoCandidato.confirmaExclusao(tfCPF.getText(), senhaAnterior)){
           JOptionPane.showMessageDialog(this, "Exclusão realizada com sucesso!", "Erro", javax.swing.JOptionPane.WARNING_MESSAGE); 
           
           formPrincipal principal1 = new formPrincipal();
           principal1.setVisible(true);  

           // Fecha a TelaInicial
           this.dispose();
        }
        else{
           JOptionPane.showMessageDialog(this, "Exclusão cancelada!", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnMensageriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensageriaActionPerformed
        classMensageria.VerificaMensageriaUsuario(Usuario, tfEmail.getText()); 
    }//GEN-LAST:event_btnMensageriaActionPerformed
    private void setaImagem(){
        ImageIcon icon = new ImageIcon("C:/Users/gusta/OneDrive/Área de Trabalho/Projeto_Eleva_Equipe_E/arquivos_classes_originais/Eleva/src/main/java/resources/images/user.png");

        // Redimensionar a imagem para caber no JLabel
        Image image = icon.getImage().getScaledInstance(lblImagem.getWidth(), lblImagem.getHeight(), Image.SCALE_SMOOTH);
    
        lblImagem.setIcon(new ImageIcon(image)); // Define a imagem na JLabel
    }
    private void VerificaVisivel(){
        if (Usuario.equals("Recrutador")){
            btnEdicao.setVisible(false); // Oculta o botão
            btnEditarCurriculo.setVisible(false);
            btnExcluir.setVisible(false);
            tfCPF.setVisible(false);
            labelCPF.setVisible(false);
            tfSenha.setVisible(false);
            labelSenha.setVisible(false);
        }else if (Usuario.equals("Candidato")){
            btnCurriculo.setVisible(false); // Oculta o botão
            btnEditarCurriculo.setVisible(true);
            tfNome.setEnabled(true);  
            tfEmail.setEnabled(true);  
            tfContato.setEnabled(true);  
            tfEndereco.setEnabled(true);  
            tfExperiencia.setEnabled(true);  
            tfResumo.setEnabled(true);  
            tfCEP.setEnabled(true);  
            tfCPF.setEnabled(false);
            tfSenha.setEnabled(true);
            tfDataNascimento.setVisible(false);
            labelNascimento1.setVisible(false);
        } 
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPerfilCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPerfilCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPerfilCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPerfilCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
              
            new formPerfilCandidato(Usuario, emailUsuario).setVisible(true);
        }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnCurriculo;
    private javax.swing.JButton btnEdicao;
    private javax.swing.JButton btnEditarCurriculo;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnMensageria;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSair1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelNascimento1;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JFormattedTextField tfCEP;
    private javax.swing.JTextField tfCPF;
    private javax.swing.JFormattedTextField tfContato;
    private javax.swing.JFormattedTextField tfDataNascimento;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfExperiencia;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextArea tfResumo;
    private javax.swing.JPasswordField tfSenha;
    // End of variables declaration//GEN-END:variables
}
